### ISSUE TITLE
create report fails on windows with "Error: Invalid file path"

### ISSUE THREAD

**Issue by stokpop** [stokpop/memory-check#2]
java -jar C:\Programs\java\memorycheck\memory-check-exec-1.2.0.jar 

```
Error: Invalid file path
java.io.FileNotFoundException: Invalid file path
at java.io.FileOutputStream.<init>(Unknown Source)
at java.io.FileOutputStream.<init>(Unknown Source)
at kotlin.io.FilesKt__FileReadWriteKt.writeBytes(FileReadWrite.kt:108)
at kotlin.io.FilesKt__FileReadWriteKt.writeText(FileReadWrite.kt:134)
at kotlin.io.FilesKt__FileReadWriteKt.writeText$default(FileReadWrite.kt:134)
at nl.stokpop.memory.report.JsonReport.report(JsonReport.kt:27)
at nl.stokpop.memory.MemoryCheck.processHistos(MemoryCheck.kt:165)
at nl.stokpop.memory.MemoryCheckCli.run(MemoryCheck.kt:101)
at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:180)
at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:17)
at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:396)
at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:393)
at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:411)
at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:436)
at nl.stokpop.memory.MemoryCheckKt.main(MemoryCheck.kt:34)
```

**Comment by stokpop** [comment]
It fails because of `:` in the timestamp in filenames in windows.

Workaround for versions 1.2.1 and earlier: use an explicit id instead of the default timestamp, e.g.: --id test-123
